[package]
name = "libui-with-workerthread-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
libui = "0.3.0"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread", "sync", "time", "tokio-macros"] }
